import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/router';
import {supabase} from '../lib/supabaseClient';
import {formatJalali} from '../lib/dateFormat';
const STATUS={DRAFT:'پیش‌نویس',POSTED:'ثبت‌شده',VOIDED:'باطل‌شده'};
const money=n=>new Intl.NumberFormat('fa-IR').format(Math.round(Number(n)||0))+' تومان';
export default function InvoicePrint(){
 const router=useRouter(),{id}=router.query;const[invoice,setInvoice]=useState(undefined),[items,setItems]=useState([]),[business,setBusiness]=useState(null);const[saving,setSaving]=useState(false),[pdfing,setPdfing]=useState(false),[copied,setCopied]=useState(false);const ref=useRef(null);
 useEffect(()=>{if(!id)return;supabase.from('invoices').select('*,customers(name,phone,address)').eq('id',id).single().then(({data})=>setInvoice(data||null));supabase.from('invoice_items').select('*').eq('invoice_id',id).order('created_at').then(({data})=>setItems(data||[]));supabase.from('business_settings').select('*').eq('id','default').single().then(({data})=>setBusiness(data||null));},[id]);
 async function pdf(){if(!ref.current)return;setPdfing(true);try{const{domToPng}=await import('modern-screenshot');const{jsPDF}=await import('jspdf');if(document.fonts?.ready)await document.fonts.ready;const el=ref.current,data=await domToPng(el,{backgroundColor:'#fff',scale:2,width:el.offsetWidth,height:el.offsetHeight});const img=new Image();img.src=data;await new Promise((r,j)=>{img.onload=r;img.onerror=j});const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),m=10,ratio=Math.min((pw-2*m)/img.width,(ph-2*m)/img.height),w=img.width*ratio,h=img.height*ratio;doc.addImage(data,'PNG',(pw-w)/2,(ph-h)/2,w,h);doc.save('invoice-'+(invoice.invoice_number||id)+'.pdf');}catch(e){alert('خطا در ساخت PDF: '+(e?.message||e));}setPdfing(false);}
 async function image(){if(!ref.current)return;setSaving(true);try{const{domToPng}=await import('modern-screenshot');const data=await domToPng(ref.current,{backgroundColor:'#fff',scale:2,width:ref.current.offsetWidth,height:ref.current.offsetHeight});const a=document.createElement('a');a.download='invoice-'+(invoice.invoice_number||id)+'.png';a.href=data;a.click();}catch(e){alert('خطا در ساخت تصویر: '+(e?.message||e));}setSaving(false);}
 function sms(){const t=(business?.name||'')+'\nفاکتور '+(invoice.invoice_number||'')+' برای '+(invoice.customers?.name||'')+'\nمبلغ: '+money(invoice.total_amount)+'\nتاریخ: '+formatJalali(invoice.issue_date);return t;}
 async function prepare(){const t=sms(),p=invoice.customers?.phone?.replace(/\s/g,'')||'';if(p)window.location.href='sms:'+p+( /iPhone|iPad|iPod/.test(navigator.userAgent)?'&':'?')+'body='+encodeURIComponent(t);else try{await navigator.clipboard.writeText(t);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{alert(t)}}
 if(invoice===undefined)return <p className="p-10 text-sm text-ink/50">در حال بارگذاری…</p>;if(!invoice)return <p className="p-10 text-sm text-badText">فاکتور یافت نشد.</p>;
 return <div className="min-h-screen bg-paper py-10 px-4"><div className="max-w-2xl mx-auto"><div ref={ref} dir="rtl" className="bg-white border border-line rounded-xl p-8 print:border-0">
  <div className="flex justify-between items-start border-b border-line pb-4 mb-5"><div className="flex gap-3">{business?.logo_url&&<img src={business.logo_url} alt="لوگو" className="w-14 h-14 object-contain"/>}<div><b className="text-lg">{business?.name||''}</b><div className="text-xs text-ink/60 mt-1">{business?.address||''}</div><div className="text-xs text-ink/60" dir="ltr">{business?.phone||''}</div></div></div><div className="text-left text-sm"><div className="text-xs text-ink/50">شماره فاکتور</div><b>{invoice.invoice_number||'—'}</b><div className="text-xs text-ink/50 mt-2">صدور</div><div>{formatJalali(invoice.issue_date)}</div><div className="text-xs text-ink/50 mt-2">سررسید</div><div>{formatJalali(invoice.due_date||invoice.issue_date)}</div></div></div>
  <div className="flex justify-between mb-5"><div><div className="text-xs text-ink/50">مشتری</div><b>{invoice.customers?.name||''}</b>{invoice.customers?.phone&&<div className="text-xs text-ink/60" dir="ltr">{invoice.customers.phone}</div>}{invoice.customers?.address&&<div className="text-xs text-ink/60">{invoice.customers.address}</div>}</div><div className="text-left text-xs">وضعیت: <b>{STATUS[invoice.status]||invoice.status}</b></div></div>
  <table className="ledger mb-5"><thead><tr><th>#</th><th>شرح</th><th>تعداد</th><th>قیمت واحد</th><th>جمع</th></tr></thead><tbody>{items.length?items.map((x,i)=><tr key={x.id}><td>{i+1}</td><td>{x.product_name}</td><td>{x.quantity}</td><td>{money(x.unit_price)}</td><td>{money(Number(x.quantity)*Number(x.unit_price))}</td></tr>):<tr><td colSpan={5}>{invoice.description||'خدمات / کالا'}</td></tr>}</tbody></table>
  <div className="flex justify-end"><div className="w-full sm:w-80 text-xs space-y-1.5"><div className="flex justify-between"><span>جمع اقلام</span><span>{money(invoice.subtotal_amount)}</span></div><div className="flex justify-between"><span>تخفیف</span><span>- {money(invoice.discount_amount)}</span></div>{Number(invoice.tax_amount)>0&&<div className="flex justify-between"><span>مالیات ({invoice.tax_rate}%)</span><span>{money(invoice.tax_amount)}</span></div>}{Number(invoice.shipping_amount)>0&&<div className="flex justify-between"><span>هزینه ارسال</span><span>{money(invoice.shipping_amount)}</span></div>}<div className="flex justify-between bg-ink text-paper rounded-lg px-4 py-3 font-bold"><span>جمع کل</span><span>{money(invoice.total_amount)}</span></div></div></div>
  {invoice.description&&<div className="border-t border-line pt-4 mt-5 text-xs text-ink/60"><b>توضیحات:</b> {invoice.description}</div>}
 </div><div className="grid grid-cols-2 gap-2 mt-4 print:hidden"><button onClick={()=>window.print()} className="focus-ring bg-brass text-white rounded-md py-2 text-xs font-semibold">چاپ فاکتور</button><button onClick={pdf} disabled={pdfing} className="focus-ring bg-ink text-white rounded-md py-2 text-xs font-semibold">{pdfing?'در حال ساخت…':'دانلود PDF (A4)'}</button><button onClick={image} disabled={saving} className="focus-ring bg-surface border border-line rounded-md py-2 text-xs">{saving?'در حال ساخت…':'ذخیره تصویر'}</button><button onClick={prepare} className="focus-ring bg-good text-white rounded-md py-2 text-xs">{copied?'متن کپی شد ✓':'آماده‌سازی پیامک'}</button></div>
 </div></div>;
}
