import { useEffect,useState } from 'react';
import Layout from '../components/Layout';
import { supabase } from '../lib/supabaseClient';

export default function Profile(){
 const [user,setUser]=useState(null);const [orgs,setOrgs]=useState([]);const [name,setName]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data:{user},error}=await supabase.auth.getUser();if(error||!user){setError('نشست شما معتبر نیست.');setLoading(false);return;}setUser(user);setName(user.user_metadata?.full_name||'');const {data,error:rpcError}=await supabase.rpc('get_my_profile');if(rpcError)setError('اطلاعات سازمان بارگذاری نشد.');else setOrgs(data||[]);setLoading(false);})();},[]);
 async function save(e){e.preventDefault();setError('');setMessage('');setSaving(true);const {error}=await supabase.auth.updateUser({data:{...user.user_metadata,full_name:name.trim()}});setSaving(false);if(error)setError('ذخیره پروفایل انجام نشد.');else{setMessage('پروفایل ذخیره شد.');setUser(u=>({...u,user_metadata:{...u.user_metadata,full_name:name.trim()}}));}}
 return <Layout title="پروفایل">{loading?<div className="text-sm text-ink/60">در حال بارگذاری…</div>:<div className="max-w-xl bg-surface rounded-xl border border-line p-5">{error&&<div className="text-badText text-xs mb-4">{error}</div>}{message&&<div className="text-goodText text-xs mb-4">{message}</div>}<div className="text-sm mb-4"><div className="text-xs text-ink/50">ایمیل</div><div className="font-medium">{user?.email||'—'}</div></div><form onSubmit={save}><label className="block text-xs text-ink/60 mb-1">نام نمایشی</label><input value={name} onChange={e=>setName(e.target.value)} className="focus-ring w-full rounded-md border border-line px-3 py-2 text-sm mb-5"/><button disabled={saving} className="focus-ring bg-brass text-white rounded-md px-4 py-2 text-sm font-semibold">{saving?'در حال ذخیره…':'ذخیره'}</button></form><div className="mt-6 pt-5 border-t border-line"><div className="text-sm font-semibold mb-3">کسب‌وکارهای متصل</div>{orgs.map(o=><div key={o.organization_id} className="flex justify-between text-sm py-2"><span>{o.organization_name}</span><span className="text-xs text-ink/50">{o.role}</span></div>)}</div></div>}</Layout>
}
