import {useEffect,useState} from 'react';
import Layout from '../components/Layout';
import {supabase} from '../lib/supabaseClient';
const MAX=512,QUALITY=.85;
function optimize(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);let{width,height}=img;if(width>MAX||height>MAX){const r=Math.min(MAX/width,MAX/height);width=Math.round(width*r);height=Math.round(height*r);}const c=document.createElement('canvas');c.width=width;c.height=height;c.getContext('2d').drawImage(img,0,0,width,height);const webp=c.toDataURL('image/webp').startsWith('data:image/webp');c.toBlob(b=>b?resolve({blob:b,ext:webp?'webp':'jpg'}):reject(new Error('empty')),webp?'image/webp':'image/jpeg',QUALITY)};img.onerror=()=>reject(new Error('load'));img.src=url;});}
export default function Settings(){
 const [form,setForm]=useState({name:'',phone:'',address:'',logo_url:'',tax_enabled:false,tax_rate:0}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{load();},[]);
 async function load(){setLoading(true);const{data}=await supabase.from('business_settings').select('*').eq('id','default').single();if(data)setForm({name:data.name||'',phone:data.phone||'',address:data.address||'',logo_url:data.logo_url||'',tax_enabled:!!data.tax_enabled,tax_rate:Number(data.tax_rate)||0});setLoading(false);}
 async function save(e){e.preventDefault();setSaving(true);setError('');const rate=Math.max(0,Math.min(100,Number(form.tax_rate)||0));const{error:e2}=await supabase.from('business_settings').update({name:form.name,phone:form.phone,address:form.address,tax_enabled:!!form.tax_enabled,tax_rate:rate,updated_at:new Date().toISOString()}).eq('id','default');setSaving(false);if(e2)return setError('خطا در ذخیره تنظیمات.');setForm(f=>({...f,tax_rate:rate}));setMessage('تنظیمات ذخیره شد.');}
 async function logo(e){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return setError('لطفاً فایل تصویری انتخاب کنید.');setSaving(true);let blob=file,ext=file.name.split('.').pop()||'jpg';try{const x=await optimize(file);blob=x.blob;ext=x.ext;}catch{}const path='logo.'+ext;const{error:ue}=await supabase.storage.from('logos').upload(path,blob,{upsert:true,cacheControl:'3600',contentType:blob.type||file.type});if(ue){setSaving(false);return setError('خطا در آپلود لوگو.');}const{data:p}=supabase.storage.from('logos').getPublicUrl(path);const url=p.publicUrl+'?t='+Date.now();const{error:de}=await supabase.from('business_settings').update({logo_url:url}).eq('id','default');setSaving(false);if(de)return setError('خطا در ذخیره لوگو.');setForm(f=>({...f,logo_url:url}));setMessage('لوگو ذخیره شد.');}
 return <Layout title="تنظیمات کسب‌وکار">{loading?<p className="text-ink/50 text-sm">در حال بارگذاری…</p>:<div className="max-w-xl">{error&&<div className="text-badText text-xs bg-bad/10 rounded-md px-3 py-2 mb-4">{error}</div>}{message&&<div className="text-goodText text-xs bg-good/10 rounded-md px-3 py-2 mb-4">{message}</div>}
 <div className="bg-surface border border-line rounded-xl p-5 mb-6"><div className="text-sm font-semibold mb-3">لوگوی کسب‌وکار</div><div className="flex items-center gap-4">{form.logo_url?<img src={form.logo_url} alt="لوگو" className="w-16 h-16 rounded-md object-contain border border-line bg-paper"/>:<div className="w-16 h-16 rounded-md border border-dashed border-line flex items-center justify-center text-xs text-ink/40">بدون لوگو</div>}<label className="focus-ring cursor-pointer text-sm text-brass">{form.logo_url?'تغییر لوگو':'آپلود لوگو'}<input type="file" accept="image/*" onChange={logo} className="hidden"/></label></div><p className="text-xs text-ink/40 mt-3">لوگو روی فاکتور چاپی نمایش داده می‌شود.</p></div>
 <form onSubmit={save} className="bg-surface border border-line rounded-xl p-5 space-y-4"><div><label className="block text-xs text-ink/60 mb-1">نام کسب‌وکار</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="focus-ring w-full rounded-md border border-line px-3 py-2 text-sm"/></div><div><label className="block text-xs text-ink/60 mb-1">شماره تماس</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} dir="ltr" className="focus-ring w-full rounded-md border border-line px-3 py-2 text-sm"/></div><div><label className="block text-xs text-ink/60 mb-1">آدرس</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="focus-ring w-full rounded-md border border-line px-3 py-2 text-sm"/></div>
 <div className="border-t border-line pt-4"><div className="font-semibold text-sm mb-3">مالیات فاکتور</div><label className="flex items-center gap-2 text-sm mb-3"><input type="checkbox" checked={form.tax_enabled} onChange={e=>setForm({...form,tax_enabled:e.target.checked})}/>فعال بودن مالیات</label><label className="block text-xs text-ink/60 mb-1">نرخ مالیات (%)</label><input type="number" min="0" max="100" step=".01" disabled={!form.tax_enabled} value={form.tax_rate} onChange={e=>setForm({...form,tax_rate:e.target.value})} className="focus-ring w-full rounded-md border border-line px-3 py-2 text-sm disabled:opacity-50"/></div>
 <button disabled={saving} className="focus-ring bg-ink text-white text-sm rounded-md px-4 py-2 font-semibold disabled:opacity-60">{saving?'در حال ذخیره…':'ذخیره تنظیمات'}</button></form></div>}</Layout>;
}
